name: Build
on:
  push:
      paths:
        - 'games/baccarat/**'
        - '.github/workflows/**'
      branches:
        - master
  pull_request:
    paths:
        - 'games/baccarat/**'
        - '.github/workflows/**'
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloudScanBaccarat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACCARAT }}
        with:
          projectBaseDir: games/baccarat/
